server:
  port: 8080
spring:
  application:
    name: pay
  datasource:
    url: jdbc:mysql://192.168.1.199:33005/dd_motorcycle_personal?useUnicode=true&characterEncoding=utf-8&generateSimpleParameterMetadata=true&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 112233
    driver-class-name: com.mysql.jdbc.Driver